name: Actions
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: setup app
       run: make setup
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: test app
       run: make test
